version: '3.8'

services:
  backend:
    image: poe_snapshot
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./PathOfBuilding:/app/PathOfBuilding
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - POB_SRC=/app/PathOfBuilding/src
      - POEX_SECRETKEY=djangosecretkey

  frontend:
    image: node:latest
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev -- --host"